export const apartments = [
  {
    picture: "https://source.unsplash.com/MP0bgaS_d1c",
    rent: 1367,
    size: 46,
    location: "Rutland Road, Springhill",
  },
  {
    picture: "https://source.unsplash.com/gREquCUXQLI",
    rent: 1368,
    size: 69,
    location: "Clinton Avenue, Norfolk",
  },
  {
    picture: "https://source.unsplash.com/3wylDrjxH-E",
    rent: 1198,
    size: 66,
    location: "Box Street, Grazierville",
  },
  {
    picture: "https://source.unsplash.com/iRiVzALa4pI",
    rent: 1432,
    size: 65,
    location: "Gerald Court, Northchase",
  },
  {
    picture: "https://source.unsplash.com/psrloDbaZc8",
    rent: 285,
    size: 57,
    location: "Bainbridge Street, Kersey",
  },
  {
    picture: "https://source.unsplash.com/FqqiAvJejto",
    rent: 1338,
    size: 77,
    location: "Dean Street, Crenshaw",
  },
  {
    picture: "https://source.unsplash.com/_-JR5TxKNSo",
    rent: 741,
    size: 74,
    location: "Ditmas Avenue, Reinerton",
  },
  {
    picture: "https://source.unsplash.com/oMOx_wV6mLQ",
    rent: 918,
    size: 77,
    location: "Vandervoort Avenue, Blue",
  },
  {
    picture: "https://source.unsplash.com/Wv65tpVIdDg",
    rent: 485,
    size: 97,
    location: "Williams Court, Wacissa",
  },
  {
    picture: "https://source.unsplash.com/DhFHtkECn7Q",
    rent: 961,
    size: 98,
    location: "Harrison Place, Shelby",
  },
  {
    picture: "https://source.unsplash.com/tHkJAMcO3QE",
    rent: 1500,
    size: 34,
    location: "Seigel Street, Coyote",
  },
  {
    picture: "https://source.unsplash.com/kdwahpWYfQo",
    rent: 821,
    size: 78,
    location: "Cook Street, Groveville",
  },
  {
    picture: "https://source.unsplash.com/OtXADkUh3-I",
    rent: 267,
    size: 34,
    location: "Estate Road, Falconaire",
  },
  {
    picture: "https://source.unsplash.com/JF5IuDNxN6M",
    rent: 765,
    size: 88,
    location: "Roosevelt Place, Stollings",
  },
  {
    picture: "https://source.unsplash.com/XyGvEj587Mc",
    rent: 886,
    size: 58,
    location: "Grattan Street, Cliff",
  },
  {
    picture: "https://source.unsplash.com/idXQEOxhmvU",
    rent: 971,
    size: 63,
    location: "Fuller Place, Bowmansville",
  },
  {
    picture: "https://source.unsplash.com/UhpYKnqZwE8",
    rent: 224,
    size: 50,
    location: "Prospect Avenue, Glendale",
  },
  {
    picture: "https://source.unsplash.com/DxLGT3bEKkE",
    rent: 1135,
    size: 75,
    location: "Benson Avenue, Moquino",
  },
];
